---
title: Integration and integral calculus
---

```{r common-r, code = xfun::read_utf8(here::here("_common.R")), include = FALSE}
```

# Definite integrals

Solve the following definite integrals using the antiderivative method.^[Gill 5.10 and Grimmer HW4.1]

For all these problems, the basic approach to compute the definite integral of $f(x)$ from $a$ to $b$ is by using the formula $F(b) - F(a)$, where $F(x)$ is the **antiderivative** of $f$.

a. $\int_6^8 x^3 \,dx$

    <!--

    **Solution:** Basic power rule. Or more so the reverse of the power rule for derivatives.
    
    $$
    \begin{aligned}
    \int_6^8 x^3 \,dx &= \left( \frac{1}{4} x^4 \right) \Big|_6^8 \\
    &= \frac{1}{4} 8^4 - \frac{1}{4} 6^4 \\
    &= \frac{4096}{4} - \frac{1296}{4} \\
    &= 1024 - 324 \\
    &= 700
    \end{aligned}
    $$
    
    -->

a. $\int_{-1}^{0} (3x^2 -1) \,dx$

    <!--

    **Solution:** 
    
    $$
    \begin{aligned}
    \int_{-1}^{0} (3x^2 -1) \,dx &= x^3 - x \Big|_{-1}^0 \\
    &= (0^3 - 0) - ((-1)^3 - (-1)) \\
    &= 0 - (-1 + 1) \\
    &= 0 - 0 \\
    &= 0
    \end{aligned}
    $$
    
    -->

a. $\int_0^1 x^{\frac{3}{7}} \,dx$

    <!--

    **Solution:** As a general rule, we can say that the antiderivative of $x^n$ is, for values of $n$ other than -1, $\frac{x^{n+1}}{n+1}$ plus a constant that we can safely ignore when doing definite integrals of this type. Then this integral evaluates as $\frac{x^{10/7}}{10/7} \bigg|_0^1 = \frac{1^{10/7}}{10/7} - \frac{0^{10/7}}{10/7} = \frac{1}{10/7} = \frac{7}{10}$.
    
    -->

a. $\int_1^2 \left(\frac{3}{x^4} + 2\right) \,dx$

    <!--

    **Solution:** Recall that we can write the integral of a sum as the sum of integrals. Then $\int_1^2 \left(\frac{3}{x^4} + 2\right) \,dx = \int_1^2 \frac{3}{x^4} \, dx + \int_1^2 2 \, dx$. Using the same rule as in the previous part, we know this evaluates as follows: $\frac{3}{-3x^{3}}\bigg|_1^2 + 2x\bigg|_1^2 = \frac{1}{-8} - (-1) + 4 - 2 = \frac{23}{8} = 2.875$.
    
    -->

a. $\int_{-1}^{1}(14+x^2) \,dx$

    <!--

    **Solution:** 
    
    $$
    \begin{aligned}
    \int_{-1}^{1}(14+x^2) \,dx &= 14x + \frac{1}{3}x^3 \Big|_{-1}^1 \\
    &= 14(1) + \frac{1}{3}(1)^3 - (14(-1) + \frac{1}{3}(-1)^3) \\
    &= 14 + \frac{1}{3} - (-14 - \frac{1}{3}) \\
    &= 14 + \frac{1}{3} + 14 + \frac{1}{3}) \\
    &= 28 \frac{2}{3}
    \end{aligned}
    $$
    
    -->

a. $\int_1^2 \dfrac{1}{t^2} \,dt$

    <!--

    **Solution:** 
    
    $$
    \begin{aligned}
    \int_1^2 \dfrac{1}{t^2} \,dt &= \left( - \frac{1}{t} \right) \Big|_1^2 \\
    &= - \frac{1}{2} - - \frac{1}{1} \\
    &= - \frac{1}{2} + 1 \\
    &= \frac{1}{2}
    \end{aligned}
    $$
    
    -->

a. $\int_2^4 e^y \,dy$

    <!--

    **Solution:** 
    
    $$
    \begin{aligned}
    \int_2^4 e^y \,dy &= e^y \Big|_2^4 \\
    &= e^4 - e^2 \\
    &\approx 47.209
    \end{aligned}
    $$
    
    -->

a. $\int_8^9 2^x \,dx$

    <!--

    **Solution:** As a general rule, the antiderivative of $a^x$ (where $a$ is a constant) is $\frac{a^x}{\ln a}$ plus a constant.
    
    $$
    \begin{aligned}
    \int_8^9 2^x \,dx &= \frac{2^x}{\log 2} \Big|_8^9 \\
    &= \frac{2^9}{\log 2} - (\frac{2^8}{\log 2}) \\
    &= \frac{2^8}{\log 2} \\
    &= \frac{256}{\log 2} \\
    &\approx 369.33
    \end{aligned}
    $$
    
    -->

a. $\int_3^3 \sqrt{x^5 + 2} \,dx$

    <!--

    **Solution:** This question is a bit sneaky. Trying to find the antiderivative of this function would be far from trivial. However, we do not actually need to do so! Notice that we are evaluating the integral from 3 to 3. Whatever the antiderivative function $F$ actually is, $F(3) - F(3) = 0$, and 0 is the solution. Intuitively, this should make sense - in effect, we are taking the area under the curve at a single point. In other words, we are taking the area of a line, and a line has no area.
    
    -->

# Applied integration

A group of three unidentified first-year graduate students at the University of Chicago are worn out after a week of math camp. Wanting to unwind, the students agree to not talk about math and decide to chat over some casual drinks at Medici.

After five shots of tequila each, two pitchers of beer, a bottle of wine, and a large Chicago-style pizza, the three students have had enough fun and decide to start the trip back home.

* Student $A$ gets on a bike and starts pedaling away at a velocity of $v_A(t) = 2t^4 + t$, where $t$ represents minutes. However, the student crashes into the side of an Uber and ends the journey after only 2 minutes.
* Student $B$ has no bike, so starts running at a velocity of $v_B(t) = 4\sqrt{t}$. Sadly, after only 4 minutes, the student's legs give out and the student decides to sing a song, instead.
* Student $C$ can't even stand up, so has no choice but to slowly crawl at a velocity of $v_C(t) = 2e^{-t}$. Student $C$ steadily plods along for 20 minutes before falling asleep on the sidewalk.

Generally, if an object moves along a straight line with position function $s(t)$, then its velocity is $v(t) = s'(t)$. The Fundamental Theorem of Calculus then tells us that

$$
\begin{aligned}
\textrm{Total distance traveled} &= \int_{t_1}^{t_2} v(t) \,dt\\
s(t_2) - s(t_1) &= \int_{t_1}^{t_2} v(t) \,dt
\end{aligned}
$$

Without using a calculator, use this formula to find the distance traveled by Students $A$, $B$, and $C$. (Assume, however unrealistic in may be, that all three students traveled in a straight line.) Who traveled the farthest? The least far?^[Grimmer HW4.2]

<!--

**Solution:** For Student $A$:

$$\int_{0}^2 2t^4 + t = \frac{2}{5}t^5 + \frac{1}{2}t^2 \bigg|_0^2 = \frac{2}{5} (2^5) + \frac{1}{2}(2^2) - \left[\frac{2}{5} (0^5) + \frac{1}{2}(0^2)\right] = \frac{2(32)}{5} + \frac{4}{2} - [0 + 0] = \frac{64}{5} + 2 = \frac{74}{5}$$

For Student $B$:

$$\int_0^4 4\sqrt{t} = 4\left(\frac{2}{3}\right) t^{3/2} \bigg|_0^4 = \frac{8}{3}(4^{3/2}) - \frac{8}{3} (0^{3/2}) = \frac{8}{3} \left(\sqrt{4^3}\right) - 0 = \frac{8}{3} \sqrt{64} = \frac{8}{3} (8) = \frac{64}{3}$$

For Student $C$:

$$\int_0^{20} 2e^{-t} = -2e^{-t} \bigg|_0^{20} = -2e^{-20} - [-2e^{0}] = -2e^{-20} + 2(1) = -\frac{2}{e^{20}} + 2 \approx 0 + 2 = 2$$

Clearly, Student $C$ had the shortest trip. We can also eyeball that Student $B$ traveled just a bit more than 20 units of distance, while $A$ went a little less than 15. If you want concrete numbers to perform the comparison, you can calculate the quotients or find a common denominator for $\frac{64}{3}$ and $\frac{74}{5}$. You'd see that Student $A$ went $\frac{222}{15}$ while $B$ went $\frac{320}{15}$. Student $B$ went the farthest. (But nobody made it home.)

-->

# Indefinite integrals

Calculate the following indefinite integrals:^[Gill 5.13 and 5.14]

a. $\int (x^2-x^{-\frac{1}{2}}) \,dx$

    <!--

    $$\int (x^2-x^{-\frac{1}{2}}) \,dx = \frac{1}{3}x^3 - 2 \sqrt{x} + c$$
    
    -->

a. $\int 360t^6 \,dt$

    <!--

    $$\int 360t^6 \,dt = \frac{360}{7} t^7 + c$$
    
    -->

a. $\int 2x\log(x^2) \,dx$

    <!--

    **Solution:** This integral requires **integration by parts**.
    
    $$\int p'(x)q(x) dx = p(x)q(x) - \int p(x)q'(x) dx$$
    
    $$
    \begin{aligned}
    p(x) &= x^2 \\
    p'(x) &= 2x \,dx \\
    q(x) &= \log(x^2) \\
    q'(x) &= \frac{2}{x} \,dx
    \end{aligned}
    $$
    
    $$
    \begin{aligned}
    \int p'(x)q(x) dx &= p(x)q(x) - \int p(x)q'(x) dx \\
    &= x^2 \log(x^2) - \int x^2 \frac{2}{x} \,dx \\
    &= x^2 \log(x^2) - \int 2x \,dx \\
    &= x^2 \log(x^2) - x^2 + c
    \end{aligned}
    $$
    
    -->

# Determining convergence

Determine whether each integral is convergent or divergent. Evaluate those that are convergent.^[Grimmer HW 4.3]

a. $\int_1^{\infty} \left(\frac{1}{3x}\right)^2 \,dx$

    <!--

    **Solution:** To find whether this integral converges and what it converges to, we must evaluate the limit $\lim_{t \to \infty} \int_1^t \frac{1}{9x^2} \, dx$. By standard rules of integration, this integral evaluates to $-\frac{1}{9x} \bigg|_1^t = -\frac{1}{9t} - (-\frac{1}{9}) = \frac{1}{9}(1-\frac{1}{t})$. As $t$ goes to infinity, $\frac{1}{t}$ goes to 0. Therefore $\lim_{t \to \infty} \frac{1}{9}(1-\frac{1}{t}) = \frac{1}{9}(1) = \frac{1}{9}$, and the integral converges to this value.
    
    -->
    
a. $\int_0^{\infty} \cos (x) \, dx$

    <!--

    **Solution:** Following the same procedure as before, we must evaluate the limit $\lim_{t \to \infty} \int_0^t \cos(x) \, dx$. This integral evaluates to $\sin(x) \bigg|_0^t = \sin(t) - \sin(0)$. Since $\sin(0) = 0$, this is equal to $\sin(t)$. But $\lim_{t \to \infty} \sin(t)$ does not exist - the value of the sine function oscillates continuously along the [-1,1] interval, and does not converge to any value as $t$ goes to infinity. Therefore the integral diverges.
    
    -->
    
a. $\int_0^{\infty} e^{-x} \,dx$

    <!--

    **Solution:** Again, the limit we need to evaluate is $\lim_{t \to \infty} \int_0^t e^{-x} \, dx$. This integral evaluates to $-e^{-x} \bigg|_0^t$ - technically, we would probably use the substitution rule here, but it is easy to see that this is the correct antiderivative even without it. This evaluation equals $-e^{-t} - (-e^0) = -e^{-t} + 1$. As $t$ goes to infinity, $e^{-t}$ goes to 0. Then $\lim_{t \to \infty} (1 - e^{-t}) = 1 - 0 = 1$, so this integral converges to 1.
    
    -->
    
a. $\int_{-\infty}^0 x^3 \,dx$

    <!--

    **Solution:** The integral we need to evaluate here is slightly different, because we are dealing with an infinite lower bound on the integral rather than an infinite upper bound. The limit we must evaluate is $\lim_{t \to -\infty} \int_t^0 x^3 \, dx$. This integral evaluates to $\frac{x^4}{4} \bigg|_t^0 = 0 - \frac{t^4}{4} = -\frac{t^4}{4}$. But it is obvious that the limit of $t^4$ does not exist as $t$ goes to negative infinity; therefore the integral does not converge.
    
    -->

# More integrals

Calculate the following integrals:^[Grimmer HW7.5]

a. $\int_{0}^1 \int_{2}^{3} x^2y^3 \,\, dxdy$
    
    <!--

    $$
    \begin{aligned}
     \int_{0}^1 \int_{2}^{3} x^2y^3 dxdy &= \int_0^1 [\frac{1}{3} x^3y^3 |^{x=3}_{x=2}]dy\\
     &= \int_{0}^{1} [\frac{1}{3} 3^3y^3 - \frac{1}{4} 2^3y^3] dy = \int_{0}^{1} \frac{19}{3} y^3 dy\\
     &= \frac{19}{12}y^4 |_{y=0}^{y=1} = \frac{19}{12}
    \end{aligned}
    $$
    
    -->

a. $\int_{2}^{3} \int_{0}^1 x^2y^3 \,\, dy dx$

    <!--

    $$
    \begin{aligned}
     \int_{2}^3 \int_{0}^{1} x^2y^3 dydx &= \int_2^3 [\frac{1}{4} x^2y^4 |^{y=1}_{y=0}]dx\\
     &= \int_{2}^{3} [\frac{1}{4} 1^4 x^2 - \frac{1}{4} 0^4 x^2 ] dx = \int_{2}^{3} \frac{1}{4} x^2 dx\\
     &= \frac{1}{12}x^3 |_{x=2}^{x=3} = \frac{19}{12}
    \end{aligned}
    $$
    
    A and B demonstrate the order of integration doesn't matter, you should get the same answer either way. 
    
    -->

a. $\int_{0}^1 \int_0^{\sqrt{1-x^2}} 2x^3y \, \, dy dx$

    <!--

    $$
    \begin{aligned}
    \int_{0}^1 \int_0^{\sqrt{1-x^2}} 2x^3ydydx &= \int_{0}^1 x^3 y^2 |_{y=0}^{y=\sqrt{1 - x^2}} dx\\
    &= \int_0^1 x^3 (1 - x^2) dx = \int_0^1 x^3 - x^5 dx\\
    &= \frac{1}{4} x^4 - \frac{1}{6}x^6 |_{x=0}^{x=1} = \frac{1}{12}
    \end{aligned}
    $$
    
    -->
